### PR TITLE
Added yargs to list of popular alternatives in /docs

### PR DESCRIPTION
**Pull request by dvidsilva**
*Issue number of the reported bug or feature request: #15 

**Describe your changes**
Added a short paragraph about yargs to the popular alternatives 

**Testing performed**
it compiles locally 

**Additional context**
congrats on the launch

### CODE REVIEW

**Review by molisani — CHANGES_REQUESTED** [review]
Thanks for the contribution! Make sure you sign off your commits so that the DCO check is happy.

We did mention Yargs in the Common Patterns section under Method Chaining, but I agree that yargs is ubiquitous enough that it could be repeated under Popular Libraries.

That being said, I would want any description of the library to mention that its approach to TypeScript support requires types to be defined in the parser and then consumed by the implementation (rather than the other way around, which is the approach that Stricli takes).

**Comment by dvidsilva** [comment]
makes total sense, thanks - making a change to include that. 

also I just realized that it is installed in node_modules, is a dependency of some of the dependencies of the package.

**Comment by mkubilayk** [comment]
@dvidsilva Can you sign off your last commit as well please?

https://github.com/bloomberg/stricli/pull/16/checks?check_run_id=31527772548 contains instructions.

**Comment by dvidsilva** [comment]
@mkubilayk thanks! just did and force pushed.

**Comment by molisani** [comment]
I've rebased the changes but it looks like the DCO check is still not passing.

> Expected "Daveed [daveed@santocabron.com](mailto:daveed@santocabron.com)", but got "David Silva [cali@hey.com](mailto:cali@hey.com)".

It looks like there's just some mismatch between your local git config and your GitHub profile.

**Comment by dvidsilva** [comment]
right, I rebased and squashed them, one of them had a different email 

thanks

**Review by molisani — APPROVED** [review]

**Comment by molisani** [comment]
Sorry for some of the back and forth, but thank you very much for the contribution!

**Comment by dvidsilva** [comment]
Appreciated! it was a great exercise, will send more complex PRs if I run into issues locally

**Pull request merged**
